export type Step = { id:string; type:string; name:string; description:string; config:Record<string,string>; runState?:'waiting'|'running'|'complete'|'error'; runMessage?:string };
export type Flow = { id:string; name:string; description:string; updated:string; nodes:Step[]; edges?:{id:string;source:string;target:string;type?:string}[] };
export type KnowledgeEntry={id:string;title:string;category:string;summary:string;detail:string;imported?:boolean};
export const starters:Flow[] = [
 {id:'student-scores',name:'Student score review',description:'Find at-risk students from a CSV and prepare a review list.',updated:'Just now',nodes:[{id:'s1',type:'READ_CSV',name:'Read student scores',description:'Load a CSV file of student marks.',config:{file:'student_scores.csv',delimiter:','}},{id:'s2',type:'FILTER',name:'Find scores below 50',description:'Keep students who need a closer look.',config:{condition:'score < 50'}},{id:'s3',type:'DATABASE',name:'Save review records',description:'Store names and marks for follow-up.',config:{table:'student_review'}},{id:'s4',type:'OUTPUT',name:'Review list',description:'Make the resulting records available.',config:{format:'table'}}]},
 {id:'weekly-report',name:'Weekly report digest',description:'Shape weekly data into a tidy report.',updated:'Yesterday',nodes:[{id:'r1',type:'INPUT',name:'Weekly source',description:'Receive the report data.',config:{source:'weekly_export.csv'}},{id:'r2',type:'TRANSFORM',name:'Prepare summary',description:'Normalize fields and summarize totals.',config:{operation:'group by category'}},{id:'r3',type:'OUTPUT',name:'Report output',description:'Prepare a readable summary.',config:{format:'csv'}}]},
 {id:'webhook-intake',name:'Webhook intake',description:'Accept and inspect a simple incoming payload.',updated:'2 days ago',nodes:[{id:'w1',type:'HTTP_REQUEST',name:'Fetch records',description:'Request records from a source endpoint.',config:{method:'GET',url:'https://example.local/records'}},{id:'w2',type:'LLM',name:'Classify request',description:'Structure a short classification result.',config:{task:'categorize'}},{id:'w3',type:'OUTPUT',name:'Intake result',description:'Return the structured result.',config:{format:'json'}}]}
];
export const knowledge=[{id:'csv',title:'Working with CSV input',category:'Data sources',summary:'Read tabular files and identify the fields your workflow needs.',detail:'A CSV reading step needs a file path, delimiter, and a header row containing stable column names.'},{id:'filters',title:'Filter conditions',category:'Data preparation',summary:'Keep records that meet a clear, testable condition.',detail:'Use explicit comparisons such as score < 50. Conditions should refer to fields available in the incoming records.'},{id:'records',title:'Saving structured records',category:'Storage patterns',summary:'Map selected fields into a predictable record shape.',detail:'Choose the destination table and name the fields that should be preserved for later review.'},{id:'linear',title:'Linear workflow patterns',category:'Workflow design',summary:'Arrange each operation so its input comes from the previous step.',detail:'A clear linear workflow begins with an input, performs one or more transformations, and ends with an output.'}];
export const nodeKinds=[['INPUT','indigo'],['READ_FILE','blue'],['READ_CSV','blue'],['LLM','violet'],['FILTER','amber'],['TRANSFORM','teal'],['DATABASE','green'],['HTTP_REQUEST','rose'],['OUTPUT','slate']];
export const makeId=()=>Math.random().toString(36).slice(2,9);
export const supportedNodeTypes=nodeKinds.map(n=>n[0]);
export const newFlow=(name='Untitled workflow'):Flow=>({id:makeId(),name,description:'A new structured workflow.',updated:'Just now',nodes:[{id:makeId(),type:'INPUT',name:'Start',description:'Workflow input.',config:{source:'manual'}}]});
const key='jwork.flows.v1';
export const loadFlows=():Flow[]=>{try{const s=localStorage.getItem(key);return s?JSON.parse(s):starters}catch{return starters}};
export const saveFlows=(f:Flow[])=>localStorage.setItem(key,JSON.stringify(f));
export type ValidationIssue={level:'ERROR'|'WARNING';message:string;nodeId?:string};
const requiredConfig:Record<string,string[]>={INPUT:['source'],READ_FILE:['file'],READ_CSV:['file'],FILTER:['condition'],TRANSFORM:['operation'],DATABASE:['table'],HTTP_REQUEST:['method','url'],OUTPUT:['format']};
export function validateWorkflow(f:Flow,edges:{source:string;target:string}[]):ValidationIssue[]{const out:ValidationIssue[]=[];const issue=(level:ValidationIssue['level'],message:string,nodeId?:string)=>out.push({level,message,nodeId});if(!f.nodes.length){issue('ERROR','Workflow has no operations.');return out}const ids=new Set(f.nodes.map(n=>n.id));if(!f.nodes.some(n=>['INPUT','READ_FILE','READ_CSV','HTTP_REQUEST'].includes(n.type)))issue('ERROR','Workflow needs a supported input or data source operation.');f.nodes.forEach(n=>{if(!supportedNodeTypes.includes(n.type))issue('ERROR',`Unsupported operation: ${n.type}.`,n.id);if(!n.name.trim())issue('ERROR',`${n.type} is missing a name.`,n.id);if(!n.description.trim())issue('WARNING',`${n.name||n.type} needs a description.`,n.id);(requiredConfig[n.type]||[]).forEach(k=>{if(!n.config?.[k]?.trim())issue('ERROR',`${n.name||n.type} needs ?${k}? configuration.`,n.id)})});if(f.nodes[0]?.type==='OUTPUT')issue('ERROR','The first operation cannot be an output.',f.nodes[0].id);if(f.nodes[f.nodes.length-1]?.type!=='OUTPUT')issue('ERROR','Workflow has no final Output operation.',f.nodes[f.nodes.length-1]?.id);edges.forEach(e=>{if(!ids.has(e.source)||!ids.has(e.target))issue('ERROR','A connection refers to an operation that no longer exists.',ids.has(e.source)?e.source:undefined);if(e.source===e.target)issue('ERROR','An operation cannot connect to itself.',e.source)});f.nodes.forEach((n,i)=>{if(['INPUT','READ_FILE','READ_CSV'].includes(n.type)||i===0&&n.type==='HTTP_REQUEST')return;if(!edges.some(e=>e.target===n.id))issue('ERROR',`${n.name||n.type} is disconnected from its input.`,n.id)});return out}
export async function refineMock(flow:Flow,prompt:string):Promise<{flow:Flow;message:string}>{await new Promise(r=>setTimeout(r,650));const p=prompt.toLowerCase();let nodes=[...flow.nodes];const number=prompt.match(/\b(\d+(?:\.\d+)?)\b/)?.[1];if(/export|csv/.test(p)&&/add|include|append|create/.test(p)){const id=makeId();nodes.push({id,type:'OUTPUT',name:'Export CSV',description:'Prepare a downloadable CSV result.',config:{format:'csv'}});return{flow:{...flow,nodes},message:'Added an Output step configured for CSV export.'}}if(/remove|delete/.test(p)&&/database|storage|save/.test(p)){const removed=nodes.find(n=>n.type==='DATABASE');nodes=nodes.filter(n=>n!==removed);return removed?{flow:{...flow,nodes},message:'Removed the database operation.'}:{flow,message:'There is no database operation to remove.'}}if(/filter|threshold|score|condition/.test(p)&&number){const target=nodes.find(n=>n.type==='FILTER');if(target){const updated={...target,config:{...target.config,condition:`score < ${number}`}};nodes=nodes.map(n=>n.id===updated.id?updated:n);return{flow:{...flow,nodes},message:`Updated the filter condition to use ${number}.`}}}if(/simpler|simplify/.test(p)){const optional=nodes.find(n=>n.type==='TRANSFORM'||n.type==='LLM');if(optional){nodes=nodes.filter(n=>n!==optional);return{flow:{...flow,nodes},message:`Removed ${optional.name} to simplify the flow.`}}return{flow,message:'This flow has no optional transformation to remove.'}}if(/http|request/.test(p)&&/add|after|include/.test(p)){const id=makeId();nodes.splice(Math.max(0,nodes.length-1),0,{id,type:'HTTP_REQUEST',name:'Fetch additional data',description:'Request related records from a source.',config:{method:'GET',url:'https://example.local/data'}});return{flow:{...flow,nodes},message:'Added an HTTP request before the final output.'}}return{flow,message:'I could not map that refinement to a supported edit. Try adding an export, changing a filter threshold, or removing the database step.'}}
export async function generateMock(prompt:string):Promise<Flow>{await new Promise(r=>setTimeout(r,1100));if(prompt.toLowerCase().includes('error'))throw new Error('The request could not be mapped to the current set of supported operations. Try a simpler, linear task.');return {...newFlow(prompt.length>38?prompt.slice(0,38).trim()+'…':prompt||'Generated workflow'),description:prompt,nodes:[{id:makeId(),type:'READ_CSV',name:'Read source data',description:'Load the input records.',config:{file:'input.csv',delimiter:','}},{id:makeId(),type:'FILTER',name:'Filter matching records',description:'Keep rows that match your request.',config:{condition:'add your condition'}},{id:makeId(),type:'OUTPUT',name:'Review results',description:'Prepare the filtered result.',config:{format:'table'}}]}}
export async function simulateFlow(flow:Flow,onNode:(nodeId:string,state:Step['runState'],message:string)=>void){const records=[{student:'Amina',score:42},{student:'Daniel',score:67},{student:'Mei',score:38}];for(let i=0;i<flow.nodes.length;i++){const n=flow.nodes[i];onNode(n.id,'running',`Running ${n.name}…`);await new Promise(r=>setTimeout(r,650));if(n.type==='HTTP_REQUEST'&&n.config.url?.includes('invalid')){onNode(n.id,'error','Request failed: invalid endpoint.');throw new Error(`${n.name} could not complete. Check the endpoint.`)}if(n.type==='FILTER'){const limit=Number(n.config.condition?.match(/\d+(?:\.\d+)?/)?.[0]||50);const filtered=records.filter(r=>r.score<limit);onNode(n.id,'complete',`${filtered.length} of ${records.length} records matched.`)}else if(n.type==='OUTPUT')onNode(n.id,'complete',`${records.length} simulated records prepared.`);else onNode(n.id,'complete',`${n.name} completed (simulated).`)}return{rows:records.filter(r=>r.score<Number(flow.nodes.find(n=>n.type==='FILTER')?.config.condition?.match(/\d+/)?.[0]||50)),message:'Simulation completed. Sample records were processed in memory.'}}
